### ISSUE TITLE
As new user I can create an account in the system

### ISSUE THREAD

**Issue by rpazda** [ucf-poop17/grand-hotel#1]
## Details
Basic account creation. Form for inputting account information and application code to create the account, log the user in, and direct them to the correct page

## Acceptance Criteria
- User can access form to input account information
- User can submit account data
- Form prevents user from leaving fields blank and submitting
- Form prevents invalid input on fields with formatted information, such as email
- Fields that can be standardized use simplified UI are used where possible
- All inputted account data is stored in database
- Database protected from injection attacks
- Password information stored as hash, rather than directly

**Comment by ih8celery** [comment]
all of these criteria have been met
