### ISSUE TITLE
As a User, I can login to the system

### ISSUE THREAD

**Issue by rpazda** [ucf-poop17/grand-hotel#2]
## Details
User with acount can log in to system. Invalid input is not accepted. Protection from injection is desirable. Invalid information should not successfully enable funtions. Pages for logged in users should be inaccessible. 

## Acceptance Criteria
- Valid users can log in to system 
- Invalid credentials are not accepted
- Users who are not logged in cannot view account-specific pages such as account, reservations, etc.
- Successful login results in redirection to the search page of the application
- Main page displays current login information for users that are currently logged in

**Comment by rpazda** [comment]
## Details
User with acount can log in to system. Invalid input is not accepted. Protection from injection is desirable. Invalid information should not successfully enable funtions. Pages for logged in users should be inaccessible. 

## Acceptance Criteria
- Valid users can log in to system 
- Invalid credentials are not accepted
- Users who are not logged in cannot view account-specific pages such as account, reservations, etc.

**Comment by rpazda** [comment]
Did not mean to close issue

**Comment by ih8celery** [comment]
this is now complete
