### ISSUE TITLE
As a User, I can create a reservation in the system

### ISSUE THREAD

**Issue by rpazda** [ucf-poop17/grand-hotel#3]
## Details
System will have interface for creating a reservation in the system. There should be a way to locate a desired room on specific day(s) and select it for reservation by a user.

## Acceptance Criteria

- User can view rooms available for reservation
- User can select room
- User can view details of room and confirm the reservation

**Comment by rpazda** [comment]
## Details
System will have interface for creating a reservation in the system. There should be a way to locate a desired room on specific day(s) and select it for reservation by a user.

## Acceptance Criteria

- User can view rooms available for reservation
- User can select room
- User can view details of room and confirm the reservation

**Comment by ih8celery** [comment]
currently the user does not "confirm" reservations. He can click the "book room" button and it will be added to his account
